application: reversi-1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: /styles
  static_dir: styles

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /.*
  script: main.app
  login: required
